version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: ["./srv"]
    networks:
      - app-network

  client:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - server
    command: ["./cli"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge