version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: nastya
      POSTGRES_PASSWORD: pgspgs
      POSTGRES_DB: clientServerApp
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d

  server:
    build:
      context: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_DSN=postgres://nastya:pgspgs@db:5432/clientServerApp?sslmode=disable
    command: ["./srv"]

  client:
    build:
      context: .
    depends_on:
      - server
    environment:
      - SERVER_URL=http://server:8080
    command: ["./cli"]